#!/bin/sh

case $BUTTON in
1)
        x="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
        dunstify "Battery info" "$x" -u normal
        ;;
esac

icon=""

batLeft="$(cat /sys/class/power_supply/BAT0/capacity)"

for battery in /sys/class/power_supply/BAT?*; do
        # If non-first battery, print a space separator.
        [ -n "${capacity+x}" ] && printf " "
        # Sets up the status and capacity
        case "$(cat "$battery/status" 2>&1)" in
        "Full") status="full" ;;
        "Discharging") status="discharging" ;;
        "Charging") status="charging" ;;
        "Not charging") status="notchaging" ;;
        "Unknown") status="unknown" ;;
        *) exit 1 ;;
        esac
        capacity="$(cat "$battery/capacity" 2>&1)"
        # full
        if [ "$status" = "full" ]; then
                icon=""
        fi

        if [ "$status" = "unknown" ]; then
                icon=""
        fi

        # discarging or not charging
        if [ "$status" = "discharging" ] || [ "$status" = "notchaging" ]; then

                if [ "$capacity" -gt 0 ] && [ "$capacity" -le 10 ]; then
                        icon="^c#bb5b3e^$capacity%^d^$batLeft%"
                        dunstify "low battery" -u critical
                fi

                if [ "$capacity" -gt 9 ] && [ "$capacity" -le 20 ]; then
                        icon="^c#bb5b3e^$capacity%^d^$batLeft%"
                fi

                if [ "$capacity" -gt 19 ] && [ "$capacity" -le 30 ]; then
                        icon="^c#bb5b3e^$capacity%^d^$batLeft%"
                fi

                if [ "$capacity" -gt 29 ] && [ "$capacity" -le 40 ]; then
                        icon="^c#f78f6f^^d^ $batLeft%"
                fi

                if [ "$capacity" -gt 39 ] && [ "$capacity" -le 50 ]; then
                        icon="^c#f78f6f^^d^$batLeft%"
                fi

                if [ "$capacity" -gt 49 ] && [ "$capacity" -le 60 ]; then
                        icon="^c#ffc6a3^^d^$batLeft%"
                fi

                if [ "$capacity" -gt 59 ] && [ "$capacity" -le 70 ]; then
                        icon="^c#ffc6a3^^d^$batLeft%"
                fi

                if [ "$capacity" -gt 69 ] && [ "$capacity" -le 80 ]; then
                        icon="^c#ffc6a3^^d^$batLeft%"
                fi

                if [ "$capacity" -gt 79 ] && [ "$capacity" -le 90 ]; then
                        icon="^c#7cca69^^d^$batLeft%"
                fi

                if [ "$capacity" -gt 89 ] && [ "$capacity" -le 100 ]; then
                        icon="^c#7cca69^^d^$batLeft%"
                fi
                if [ "$capacity" -eq 100 ]; then
                        icon="^c#7cca69^^d^"
                fi
        fi

        if [ "$status" = "charging" ]; then

                if [ "$capacity" -gt 0 ] && [ "$capacity" -le 20 ]; then
                        icon="^c#007160^^d^"
                fi

                if [ "$capacity" -gt 19 ] && [ "$capacity" -le 40 ]; then
                        icon="^c#008f65^^d^"
                fi

                if [ "$capacity" -gt 39 ] && [ "$capacity" -le 60 ]; then
                        icon="^c#35ad67^^d^"
                fi

                if [ "$capacity" -gt 59 ] && [ "$capacity" -le 80 ]; then
                        icon="^c#7cca69^^d^"
                fi

                if [ "$capacity" -gt 79 ] && [ "$capacity" -le 90 ]; then
                        icon="^c#bde66e^^d^"
                fi
                if [ "$capacity" -gt 89 ]; then
                        icon="^c#ffff7a^^d^"
                fi
        fi
        printf "%s" "$icon"
done && printf "\\n"
