#!/bin/bash

case $BUTTON in
1)
    gfx="$(optimus-manager --status | awk 'NR==3 { print $3 }')"

    if [ "$gfx" == "nvidia" ]; then
        driver="hybrid"
    else
        driver="nvidia"
    fi

    if zenity --question --text="Do you want to change to $driver ?"; then
        optimus-manager --switch $driver --no-confirm
        echo "logout and write /usr/bin/prime-switch"
    fi
    ;;
esac

 printf ^c#DED7D0^$(optimus-manager --status | awk 'NR==3 { print $5 }')^d^
