#!/bin/bash

#dunstify "Internet of things" "$con$dis" -u normal
echo "$con$dis"

case $BUTTON in
1)
	con="Connected \n"
	dis="Disconnected\n"

	while IFS="" read -r p; do
		ip="$(echo "$p" | awk '{print $1;}')"
		name="$(echo "$p" | awk '{print $2;}')"
		if ping -c1 -W1 $ip &>/dev/null; then
			temp="$(ssh pi@$ip '(vcgencmd measure_temp) | cut -c6- &')"
			wait
			con+="󰌘 $name: "$temp"\n"
		else
			dis+="󰌙 $name\n"
		fi

	done </home/helgi/.config/ip_addresses
	wait
	dunstify -u low "Internet of things" "$con$dis" -u normal
	echo "$con$dis"
	;;
esac
