#!/bin/sh

1)
	con="Connected \n"
	dis="Disconnected\n"
	declare -A arr

	arr+=(["p1"]=192.168.100.1 ["p2"]=192.168.100.50 ["p3"]=192.168.100.51 ["p4"]=192.168.100.52 ["p5"]=192.168.8.20 ["z1"]=192.168.8.10 ["z2"]=192.168.8.11 ["z3"]=192.168.8.12)

	for key in ${!arr[@]}; do
		# echo ${key} ${arr[${key}]}

		if ping -c1 -W1 ${arr[${key}]} &>/dev/null; then
			temp=$(ssh pi@${arr[${key}]} '(vcgencmd measure_temp)')
			temp="${temp:5}"
			temp=${temp::-4}
			con+="󰌘 ${key}: "$temp"C\n"
		else
			dis+="󰌙 ${key}: no connection\n"
		fi
	done
	dunstify "Internet of things" "$con$dis" -u normal
esac
