#!/bin/sh
# works on any init system
# requirements: dmenu, xorg-setxkbmap
kb="$(setxkbmap -query | grep -oP 'layout:\s*\K\w+')" || exit 1
[[ "$kb" == "us" ]] && printf "^c#ffff7a^󰥻^d^" || printf "^c#00f5ff^󰥻^d^"

