#!/bin/zsh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

case $BUTTON in
    1) setsid alacritty -e newsboat ;;
    2) setsid -f newsup >/dev/null exit ;;
    3) st -e code "$0" ;;
esac

stories="$(newsboat -x print-unread | awk '{print $1}')"
if [ "$stories" = "Error:" ]; then
    printf "^c#2f4858^a ^d^"
else
    if [ "$stories" -eq 0 ]; then
        printf "^c#bb5b3e^b ^d^"
    fi

    if [ "$stories" -gt 0 ] && [ "$stories" -le 4 ]; then
        printf "^c#ffc6a3^b ^d^"
    fi
    
    if [ "$stories" -gt 3 ]; then
        printf "^c#35ad67^c ^d^"
    fi
fi
