#!/bin/zsh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

case $BUTTON in
        1) setsid alacritty -e newsboat ;;
	2) setsid -f newsup >/dev/null exit ;;
        3) st -e code "$0" ;;
esac

x=$(newsboat -x print-unread | awk '{ if($1>0) print  $1}')
if [ "$x" -eq "$x" ] 2>/dev/null; then
  echo " "$x
else
  echo " "
fi