#!/bin/zsh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

case $BUTTON in
        1) setsid alacritty -e newsboat ;;
	2) setsid -f newsup >/dev/null exit ;;
        3) st -e code "$0" ;;
esac
a="$(newsboat -x print-unread | awk '{print $1}')"

if [ "$a" = "Error:" ]; then
    echo " ?"
else
    echo " " "$a"
fi
