#!/bin/sh


red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
s=""

declare -A arr

arr+=(["epaper"]=192.168.1.10 ["led_matrix"]=192.168.1.11)

for key in ${!arr[@]}; do
	# echo ${key} ${arr[${key}]}

	if ping -c1 -W1 ${arr[${key}]} &>/dev/null; then
		i=$(ssh pi@${arr[${key}]} '(systemctl show -p ActiveState --value '${key}')');
		case $i in
    		active) s+="${key}: ACTIVE \n";;
    		inactive) s+="${key}: INACTIVE \n";;
		esac
	else
		s+="󰌙 ${arr[${key}]} no connection"
	fi
done

case $BUTTON in
        1) dunstify "System services" "${s}" -u normal ;;	
esac
## now loop through the above array

# You can access them using echo "${arr[0]}", "${arr[1]}" also

# icon="󰌗"
