#!/bin/bash
case $BUTTON in
1)
    x=$(zenity --entry --entry-text="" --text="Question")
    if [ "$x" ]; then
        answer=$(tuxi -r $x)
        dunstify "$x" "$answer?" -u normal
    fi
    ;;
3)
    ticker=$(zenity --entry --entry-text="" --text="Stock quote")
    if [ "$ticker" ]; then
        a=$(curl -s "https://query1.finance.yahoo.com/v7/finance/quote?symbols=SAVA" | jq -r '.quoteResponse["result"][0] | "" + (.regularMarketPrice|tostring) +"  "+ (.regularMarketChangePercent|tostring)+"%"')
        rounded=$(printf "%.3f\n" "$a")
        dunstify "Price" "$ticker: $a" -u normal
    fi
    ;;
esac
