#!/bin/sh
volon=$(amixer get Master | awk -F'[][]' 'END{ print $6 }')

vol=$(amixer get Master | awk -F'[][]' 'END{ print $2 }')

mic=$(amixer get Capture | awk -F'[][]' 'END{ print $6 }')
micvol=$(amixer get Capture | awk -F'[][]' 'END{ print $2 }')

icon=""
icon2=""
if [[ "$mic" = 'on' ]]; then
	icon=""
else
	icon=""
fi

if [[ "$volon" = 'on' ]]; then
	amixer -q sset Headphone on
	icon2="󰕾"
else
	icon2="󰖁"
fi

case $BUTTON in
1) dunstify "Alsamixer" "$icon $micvol\n$icon2 $vol" -u normal ;;
2) st -e alsamixer ;;
3) st -e code "$0" ;;
esac

echo $vol