#!/bin/sh
volon=$(amixer get Master | awk -F'[][]' 'END{ print $6 }')

tmp=$(amixer get Master | awk -F'[][]' 'END{ print $2 }')
vol=${tmp::-1}

mic=$(amixer get Capture | awk -F'[][]' 'END{ print $6 }')
micvol=$(amixer get Capture | awk -F'[][]' 'END{ print $2 }')
icon=""

case $BUTTON in
1) dunstify -u low "󰕾" "$icon $micvol\n$icon2 $vol" -u normal ;;
2) alacritty -e alsamixer ;;
3) alacritty -e dwm_vol vol && pkill -RTMIN+5 dwmblocks ;;
4)
    dwm_vol up
    dunstify -u low -r 31 -h int:value:$vol "󰕾"
    ;;
5)
    dwm_vol down
    dunstify -u low -r 31 "󰕾" -h int:value:$vol 
    ;;
esac

if [[ "$mic" = 'on' ]]; then
    icon=""
else
    icon="^c#f78f6f^^d^"
fi

if [[ "$volon" = 'on' ]]; then
    amixer -q sset Headphone on
    if [ "$vol" -gt 0 ] && [ "$vol" -le 25 ]; then
        printf "^c#bb5b3e^󰕾^d^$icon"
    fi
    if [ "$vol" -gt 25 ] && [ "$vol" -le 50 ]; then
        printf "^c#f78f6f^󰕾^d^$icon"

    fi
    if [ "$vol" -gt 49 ] && [ "$vol" -le 75 ]; then
        printf "^c#ffc6a3^󰕾^d^$icon"

    fi
    if [ "$vol" -gt 74 ]; then
        printf "^c#ffff7a^󰕾^d^$icon"
    fi
else
    printf "^c#f78f6f^󰖁^d^$icon"
fi
