#!/bin/bash

case $BUTTON in
1)
    sudo nmcli dev wifi rescan

    networks="$(nmcli --terse --fields SSID device wifi | sed -z 's/\n/\\n/g;s/\\$//' | sed 's/.\{2\}$//')"

    network="$(echo -e $networks | dmenu -z 295 -p "network")"
    if [ -n "$network" ]; then
        pass=$(zenity --password --text="Password")
        if [ -n "$pass" ]; then
            sudo nmcli d wifi connect $network password $pass
            pkill -RTMIN+8 dwmblocks
        fi
    fi
    ;;
esac

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null; then
    wifiicon=""
    wifistring=""
    vpn="$(sed "s/.*//" /sys/class/net/nordlynx*/operstate 2>/dev/null)"

    if [ ! -z "$vpn" ]; then
        wifiicon=$vpn
    fi

    tmp="$(awk 'NR==3 {printf $3}' /proc/net/wireless)"
    wifisignal=${tmp::-1}
    wifiname="$(nmcli -f IN-USE,SIGNAL,SSID device wifi | awk '/^\*/{if (NR!=1) {print $3}}')"
    if [ "$wifisignal" -gt 0 ] && [ "$wifisignal" -le 25 ]; then
        wifistring="^c#bb5b3e^$wifiicon^d^"
    fi
    if [ "$wifisignal" -gt 25 ] && [ "$wifisignal" -le 50 ]; then
        wifistring="^c#f78f6f^$wifiicon^d^"

    fi
    if [ "$wifisignal" -gt 49 ] && [ "$wifisignal" -le 75 ]; then
        wifistring="^c#ffc6a3^$wifiicon^d^"

    fi
    if [ "$wifisignal" -gt 74 ]; then
        wifistring="^c#7cca69^$wifiicon^d^"
    fi

elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null; then
    wifistring=""
fi

printf "%s""$wifistring $wifiname"
